Blog.WebUI/Controllers/AuthController.cs
using Blog.Business.Dtos.UserDtos;
using Blog.Business.Services;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using Blog.WebUI.Models;

namespace Blog.WebUI.Controllers
{
    public class AuthController : Controller
    {
        private readonly IUserService _userService;

        public AuthController(IUserService userService)
        {
            _userService = userService;
        }

        [HttpGet]
        [Route("Auth/AccessDenied")]
        public IActionResult AccessDenied()
        {
            return View();
        }
        [HttpGet]
        [Route("KayitOl")]
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost]
        [Route("KayitOl")]
        public IActionResult Register(RegisterViewModel formData)
        {
            if (!ModelState.IsValid)
            {
                return View(formData);
            }
            var addUserDto = new AddUserDto()
            {
                Email = formData.Email.Trim(),
                FirstName = formData.FirstName.Trim(),
                LastName = formData.LastName.Trim(),
                Password = formData.Password.Trim(),
            };
            var result = _userService.AddUser(addUserDto);
            if (result.IsSucceed)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ViewBag.ErrorMessage = result.Message;
                return View(formData);
            }


        }
        public async Task<IActionResult> Login(LoginViewModel formData)
        {
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Index", "Home");
            }

            var loginDto = new LoginDto()
            {
                Email = formData.Email,
                Password = formData.Password
            };

            var userInfo = _userService.LoginUser(loginDto);
            if (userInfo is null)
            {
                return RedirectToAction("Index", "Home");
            }

            var claims = new List<Claim>
    {
        new Claim(ClaimTypes.NameIdentifier, userInfo.Id.ToString()), 
        new Claim("id", userInfo.Id.ToString()),
        new Claim("email", userInfo.Email),
        new Claim("firstName", userInfo.FirstName),
        new Claim("lastName", userInfo.LastName),
        new Claim("userType", userInfo.UserType.ToString()),
        new Claim(ClaimTypes.Role, userInfo.UserType.ToString())
    };

            var claimIdentity = new ClaimsIdentity(claims, CookieAuthenticationDefaults.AuthenticationScheme);
            var authProperties = new AuthenticationProperties
            {
                AllowRefresh = true,
                ExpiresUtc = DateTimeOffset.UtcNow.AddHours(99)
            };

            await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme, new ClaimsPrincipal(claimIdentity), authProperties);
            return RedirectToAction("Index", "Home");
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync();

            return RedirectToAction("Index", "Home");
        }
    }
}

Blog.WebUI/Controllers/UserController.cs
using Blog.Business.Dtos.UserDtos;
using Blog.Business.Services;
using Blog.WebUI.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace Blog.WebUI.Controllers
{
    [Authorize]
    public class UserController : Controller
    {
        private readonly IUserService _userService;
        private readonly IWebHostEnvironment _environment;

        public UserController(IUserService userService, IWebHostEnvironment environment)
        {
            _userService = userService;
            _environment = environment;
        }

        [HttpGet]
        public IActionResult Profile()
        {
            var userId = int.Parse(User.FindFirst(ClaimTypes.NameIdentifier)?.Value);
            var user = _userService.GetUserById(userId);

            if (user == null)
            {
                return RedirectToAction("Index", "Home");
            }

            var model = new ProfileViewModel
            {
                Id = user.Id,
                FirstName = user.FirstName,
                LastName = user.LastName,
                Email = user.Email,
                ProfileImageUrl = user.ProfileImageUrl
            };

            return View(model);
        }

        [HttpPost]
        public IActionResult Profile(ProfileViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var loggedInUserId = int.Parse(User.FindFirst(ClaimTypes.NameIdentifier)?.Value);

            if (model.Id != loggedInUserId)
            {
                ViewBag.ErrorMessage = "Kullanıcı bilgileri uyuşmuyor.";
                return View(model);
            }

            var newFileName = model.ProfileImageUrl;

            if (model.ProfileImage != null)
            {
                var allowedFileTypes = new string[] { "image/jpeg", "image/jpg", "image/png", "image/jfif" };
                var allowedFileExtensions = new string[] { ".jpg", ".jpeg", ".png", ".jfif" };
                var fileContentType = model.ProfileImage.ContentType;
                var fileNameWithoutExtension = Path.GetFileNameWithoutExtension(model.ProfileImage.FileName);
                var fileExtension = Path.GetExtension(model.ProfileImage.FileName);

                if (!allowedFileTypes.Contains(fileContentType) || !allowedFileExtensions.Contains(fileExtension))
                {
                    ViewBag.ErrorMessage = "Desteklenmeyen dosya türü.";
                    return View(model);
                }

                newFileName = fileNameWithoutExtension + "-" + Guid.NewGuid() + fileExtension;
                var folderPath = Path.Combine("images", "profiles");

                var wwwrootFolderPath = Path.Combine(_environment.WebRootPath, folderPath);
                var wwwrootFilePath = Path.Combine(wwwrootFolderPath, newFileName);

                Directory.CreateDirectory(wwwrootFolderPath);

                using (var filestream = new FileStream(wwwrootFilePath, FileMode.Create))
                {
                    model.ProfileImage.CopyTo(filestream);
                }
            }

            var updateUserDto = new UpdateUserDto
            {
                Id = model.Id,
                FirstName = model.FirstName,
                LastName = model.LastName,
                Email = model.Email,
                ProfileImageUrl = newFileName
            };

            var result = _userService.UpdateUser(updateUserDto);

            if (result.IsSucceed)
            {
                TempData["SuccessMessage"] = "Profil başarıyla güncellendi.";
                return RedirectToAction("Profile");
            }
            else
            {
                ViewBag.ErrorMessage = result.Message;
                return View(model);
            }

        }


    }
}

Blog.WebUI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>Ali Eren Karadeniz | Blog Proje Sitesi</title>

    <meta name="description" content="Blog Proje MVC web projesi">
    <meta name="keywords" content="HTML, CSS, JavaScript, Jquery, MVC, .Net, Asp.Net, Blog ">
    <meta name="author" content="Ali Eren Karadeniz">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">

    <style>
        label.required:after {
            content: "*\00a0";
            color: darkred;
            margin-left: 3px;
        }

        .profile-image {
            width: 40px;
            height: 40px;
            object-fit: cover;
            border-radius: 50%;
            margin-right: 10px;
        }

        .welcome-profile-image {
            width: 50px;
            height: 50px;
            object-fit: cover;
            border-radius: 50%;
            margin-right: 10px;
        }
    </style>

</head>
<body class="d-flex flex-column min-vh-100">
    <div class="container">
        <header class="p-3 text-bg-dark">
            <div class="container">
                <div class="d-flex flex-wrap align-items-center justify-content-center justify-content-lg-start">
                    <a href="/" class="d-flex align-items-center mb-2 mb-lg-0 text-white text-decoration-none fw-bold">
                        Blog Uygulaması
                    </a>

                    <ul class="nav col-12 col-lg-auto me-lg-auto mb-2 justify-content-center mb-md-0">
                        <li class="nav-item" style="margin-left:15px">
                            <a class="nav-link text-blue" asp-controller="Article" asp-action="Index">Makale</a>
                        </li>
                        <li class="nav-item" style="margin-left:2px">
                            <a class="nav-link text-blue" asp-controller="User" asp-action="Profile">Profil</a>
                        </li>
                    </ul>

                    <div class="d-none" id="login">
                        <partial name="_LoginPartial" model="new LoginViewModel()">
                    </div>

                    @if (!User.IsLogged())
                    {
                        <div id="welcome">
                            <partial name="_WelcomePartial">
                        </div>
                    }
                    else
                    {
                        var firstName = User.GetUserFirstName();
                        var lastName = User.GetUserLastName();
                       

                        <div class="d-flex align-items-center">                           
                            <div class="text-white ms-2">
                                Hoş Geldin @firstName @lastName
                            </div>
                            <a asp-controller="Auth" asp-action="Logout" class="btn btn-outline-danger ms-3">Çıkış Yap</a>
                        </div>
                    }
                </div>
            </div>
        </header>
    </div>
    <div class="container">
        @RenderBody()
    </div>
    <footer class="bg-dark text-white text-center fw-bold py-5 mt-auto">
        Blog
        <p class="text-secondary">Tüm Hakları Ali Eren Karadeniz'e aittir.</p>
    </footer>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js" integrity="sha512-v2CJ7UaYy4JwqLDIrZUI/4hqeoQieOmAZNXBeQyjo21dadnwR+8ZaIJVT8EE2iyI61OV8e6M8PP2/4hpQINQ/g==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>

    <script>
        $('#btnGirisYap').click(function () {
            $('#login').removeClass('d-none');
            $('#welcome').addClass('d-none');
        });
        $('#btnIptal').click(function () {
            $('#login').addClass('d-none');
            $('#welcome').removeClass('d-none');
        });
    </script>

</body>
</html>

Blog.WebUI/Views/Shared/_WelcomePartial.cshtml
<div class="text-end">
	<button id="btnGirisYap" type="button" class="btn btn-outline-light me-2">Giriş Yap</button>
	<a asp-controller="Auth" asp-action="Register" class="btn btn-outline-secondary">Kayıt Ol</a>
</div>